version: '3'
services:
  main_app:
    image: kirillka564/main_app:latest
    build:
      context: .
      dockerfile: main_app/Dockerfile
    ports:
      - "1024:1024"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./common:/app/common
      - ./config.py:/app/config.py
    networks:
      - swipe_network
    env_file:
      - .env

  socket_app:
    image: kirillka564/socket_app:latest
    build:
      context: .
      dockerfile: socket_app/Dockerfile
    ports:
      - "1025:1025"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./common:/app/common
      - ./config.py:/app/config.py
    networks:
      - swipe_network
    env_file:
      - .env

  push_app:
    image: kirillka564/push_app:latest
    build:
      context: .
      dockerfile: push_app/Dockerfile
    ports:
      - "1026:1026"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./common:/app/common
      - ./config.py:/app/config.py
    networks:
      - swipe_network
    env_file:
      - .env

  admin_app:
    image: kirillka564/admin_app:latest
    build:
      context: .
      dockerfile: admin_app/Dockerfile
    ports:
      - "1027:1027"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./common:/app/common
      - ./config.py:/app/config.py
    networks:
      - swipe_network
    env_file:
      - .env

networks:
  swipe_network:
    driver: bridge
