version: '3'
services:
  main_app:
    build: ./main_app
    ports:
      - "1024:1024"
    environment:
      - PYTHONPATH=/app/common
    volumes:
      - ./common:/app/common
      - ./config.py:/app/config.py
    env_file:
      - .env
  matches_app:
    build: ./matches_app
    ports:
      - "1025:1025"
    environment:
      - PYTHONPATH=/app/common
    volumes:
      - ./common:/app/common
      - ./config.py:/app/config.py
    env_file:
      - .env