"""Head Migration

Revision ID: 3ece68983ddb
Revises: 
Create Date: 2024-11-04 20:20:30.929860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ece68983ddb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.alter_column('chats', 'user1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chats', 'user2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.create_index(op.f('ix_cities_city_name'), 'cities', ['city_name'], unique=False)
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_index(op.f('ix_cities_region_id'), 'cities', ['region_id'], unique=False)
    op.alter_column('date_invitations', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('date_invitations', 'recipient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('date_invitations', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    invitation_status_enum = postgresql.ENUM(
        'pending', 'accepted', 'declined', name='invitation_status_enum'
    )
    # Create the ENUM type in the database
    invitation_status_enum.create(op.get_bind())

    # Remove the existing default value
    op.alter_column(
        'date_invitations',
        'status',
        server_default=None,
        existing_type=sa.VARCHAR(),
    )

    # Alter the column data type with casting
    op.alter_column(
        'date_invitations',
        'status',
        type_=invitation_status_enum,
        existing_nullable=True,
        postgresql_using="status::invitation_status_enum",
    )

    # Set the new default value
    op.alter_column(
        'date_invitations',
        'status',
        server_default=sa.text("'pending'"),
        existing_type=invitation_status_enum,
    )
    op.create_index(op.f('ix_dislikes_id'), 'dislikes', ['id'], unique=False)
    op.alter_column('favorites', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('favorites', 'favorite_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_likes_id'), 'likes', ['id'], unique=False)
    op.alter_column('media', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column(
        'media',
        'media_type',
        type_=sa.Text(),
        existing_type=sa.Enum('text', 'voice', 'image', name='message_type_enum'),
        existing_nullable=True,
        postgresql_using="media_type::text",
    )
    media_type_enum = postgresql.ENUM('text', 'voice', 'image', name='media_type_enum')
    media_type_enum.create(op.get_bind())

    op.alter_column(
        'media',
        'media_type',
        type_=media_type_enum,
        existing_type=sa.Text(),
        existing_nullable=True,
        postgresql_using="media_type::media_type_enum",
    )
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.alter_column('push_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('push_tokens', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_push_tokens_id'), 'push_tokens', ['id'], unique=False)
    op.drop_constraint('refresh_tokens_refresh_token_key', 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_refresh_token'), 'refresh_tokens', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.drop_constraint('regions_name_key', 'regions', type_='unique')
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_index(op.f('ix_regions_name'), 'regions', ['name'], unique=True)
    op.alter_column('subscriptions', 'renewable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_name'), 'subscriptions', ['name'], unique=False)
    op.create_index(op.f('ix_temporary_codes_code'), 'temporary_codes', ['code'], unique=False)
    op.create_index(op.f('ix_temporary_codes_id'), 'temporary_codes', ['id'], unique=False)
    op.create_index(op.f('ix_temporary_codes_phone_number'), 'temporary_codes', ['phone_number'], unique=False)
    op.add_column('transactions', sa.Column('order_number', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('payment_id', sa.BigInteger(), nullable=False))
    op.add_column('transactions', sa.Column('payment_url', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('status', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('card_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('rebill_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_unique_constraint(None, 'transactions', ['order_number'])
    op.create_unique_constraint(None, 'transactions', ['payment_id'])
    op.alter_column('user_geolocation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_geolocation', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_interests', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_interests', 'interest_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_likes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_user_likes_id'), 'user_likes', ['id'], unique=False)
    op.alter_column('user_photos', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_photos', 'scale',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('user_photos', 'position_x',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('user_photos', 'position_y',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.create_index(op.f('ix_user_photos_id'), 'user_photos', ['id'], unique=False)
    op.add_column('user_subscriptions', sa.Column('next_billing_date', sa.DateTime(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('renewable', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.drop_constraint('users_phone_number_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.alter_column('verification_queue', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('verification_queue', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('verification_queue', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('verification_queue', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_verification_queue_id'), 'verification_queue', ['id'], unique=False)
    op.alter_column('voice_messages', 'voice_data',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voice_messages', 'voice_data',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=True)
    op.drop_index(op.f('ix_verification_queue_id'), table_name='verification_queue')
    op.alter_column('verification_queue', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('verification_queue', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('verification_queue', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('verification_queue', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint('users_phone_number_key', 'users', ['phone_number'])
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_column('user_subscriptions', 'renewable')
    op.drop_column('user_subscriptions', 'next_billing_date')
    op.drop_index(op.f('ix_user_photos_id'), table_name='user_photos')
    op.alter_column('user_photos', 'position_y',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('user_photos', 'position_x',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('user_photos', 'scale',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('user_photos', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_user_likes_id'), table_name='user_likes')
    op.alter_column('user_likes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_interests', 'interest_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_interests', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_geolocation', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_geolocation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_column('transactions', 'rebill_id')
    op.drop_column('transactions', 'card_id')
    op.drop_column('transactions', 'status')
    op.drop_column('transactions', 'payment_url')
    op.drop_column('transactions', 'payment_id')
    op.drop_column('transactions', 'order_number')
    op.drop_index(op.f('ix_temporary_codes_phone_number'), table_name='temporary_codes')
    op.drop_index(op.f('ix_temporary_codes_id'), table_name='temporary_codes')
    op.drop_index(op.f('ix_temporary_codes_code'), table_name='temporary_codes')
    op.drop_index(op.f('ix_subscriptions_name'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.alter_column('subscriptions', 'renewable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_regions_name'), table_name='regions')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.create_unique_constraint('regions_name_key', 'regions', ['name'])
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_refresh_token'), table_name='refresh_tokens')
    op.create_unique_constraint('refresh_tokens_refresh_token_key', 'refresh_tokens', ['refresh_token'])
    op.drop_index(op.f('ix_push_tokens_id'), table_name='push_tokens')
    op.alter_column('push_tokens', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('push_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.alter_column('messages', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.alter_column(
        'media',
        'media_type',
        type_=sa.Text(),
        existing_type=media_type_enum,
        existing_nullable=True,
        postgresql_using="media_type::text",
    )

    media_type_enum.drop(op.get_bind())

    op.alter_column(
        'media',
        'media_type',
        type_=sa.Enum('text', 'voice', 'image', name='message_type_enum'),
        existing_type=sa.Text(),
        existing_nullable=True,
        postgresql_using="media_type::message_type_enum",
    )
    op.alter_column('media', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_likes_id'), table_name='likes')
    op.alter_column('favorites', 'favorite_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('favorites', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_dislikes_id'), table_name='dislikes')
    op.alter_column(
        'date_invitations',
        'status',
        server_default=None,
        existing_type=invitation_status_enum,
    )

    # Alter the column back to VARCHAR with casting
    op.alter_column(
        'date_invitations',
        'status',
        type_=sa.VARCHAR(),
        existing_nullable=True,
        postgresql_using="status::VARCHAR",
    )

    # Restore the original default value if necessary
    op.alter_column(
        'date_invitations',
        'status',
        server_default=sa.text("'pending'"),
        existing_type=sa.VARCHAR(),
    )

    # Drop the ENUM type
    invitation_status_enum = postgresql.ENUM(
        'pending', 'accepted', 'declined', name='invitation_status_enum'
    )
    invitation_status_enum.drop(op.get_bind())
    op.alter_column('date_invitations', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('date_invitations', 'recipient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('date_invitations', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_cities_region_id'), table_name='cities')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_index(op.f('ix_cities_city_name'), table_name='cities')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.alter_column('chats', 'user2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chats', 'user1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
