"""Add user_attributes table and relations

Revision ID: 3ef1b88ab814
Revises: 3ece68983ddb
Create Date: 2024-11-12 20:46:36.414311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ef1b88ab814'
down_revision: Union[str, None] = '3ece68983ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('smoking_attitude', sa.Enum('NON_SMOKER', 'SOMETIMES', 'REGULAR_SMOKER', 'TRYING_TO_QUIT', 'NOT_OPPOSED', 'STYLE_LIFE', name='smokingattitudeenum'), nullable=True),
    sa.Column('alcohol_attitude', sa.Enum('ABSTAIN', 'ENJOY_SIP', 'PARTY_EVERY_DAY', 'MODERATE', 'COCKTAIL_MASTER', 'HERBAL_TEA', name='alcoholattitudeenum'), nullable=True),
    sa.Column('children_preference', sa.Boolean(), nullable=True),
    sa.Column('what_looking_for', sa.Enum('TRUE_LOVE', 'NEW_FRIENDS', 'ADVENTURES', 'SERIOUS_RELATIONSHIP', 'TRAVEL', 'UNDERSTANDING', 'FRIENDSHIP_WITH_BENEFITS', name='whatlookingforenum'), nullable=True),
    sa.Column('appearance', sa.String(), nullable=True),
    sa.Column('religion', sa.Enum('ATHEIST', 'ORTHODOX', 'CATHOLIC', 'MUSLIM', 'BUDDHIST', 'HINDU', 'SPIRITUAL', 'JUDAIST', 'OTHER', 'PREFERS_NOT_TO_SAY', name='religionenum'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_alcohol_attitude', 'user_attributes', ['alcohol_attitude'], unique=False)
    op.create_index('idx_children_preference', 'user_attributes', ['children_preference'], unique=False)
    op.create_index('idx_height', 'user_attributes', ['height'], unique=False)
    op.create_index('idx_religion', 'user_attributes', ['religion'], unique=False)
    op.create_index('idx_smoking_attitude', 'user_attributes', ['smoking_attitude'], unique=False)
    op.create_index('idx_what_looking_for', 'user_attributes', ['what_looking_for'], unique=False)
    op.create_index(op.f('ix_user_attributes_id'), 'user_attributes', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_attributes_id'), table_name='user_attributes')
    op.drop_index('idx_what_looking_for', table_name='user_attributes')
    op.drop_index('idx_smoking_attitude', table_name='user_attributes')
    op.drop_index('idx_religion', table_name='user_attributes')
    op.drop_index('idx_height', table_name='user_attributes')
    op.drop_index('idx_children_preference', table_name='user_attributes')
    op.drop_index('idx_alcohol_attitude', table_name='user_attributes')
    op.drop_table('user_attributes')
    # ### end Alembic commands ###
