"""Initial migration after history loss

Revision ID: b72e72841a97
Revises: 3ef1b88ab814
Create Date: 2024-11-12 21:07:53.067754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b72e72841a97'
down_revision: Union[str, None] = '3ef1b88ab814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('smoking_attitude', sa.Enum('NON_SMOKER', 'SOMETIMES', 'REGULAR_SMOKER', 'TRYING_TO_QUIT', 'NOT_OPPOSED', 'STYLE_LIFE', name='smokingattitudeenum'), nullable=True),
    sa.Column('alcohol_attitude', sa.Enum('ABSTAIN', 'ENJOY_SIP', 'PARTY_EVERY_DAY', 'MODERATE', 'COCKTAIL_MASTER', 'HERBAL_TEA', name='alcoholattitudeenum'), nullable=True),
    sa.Column('children_preference', sa.Boolean(), nullable=True),
    sa.Column('what_looking_for', sa.Enum('TRUE_LOVE', 'NEW_FRIENDS', 'ADVENTURES', 'SERIOUS_RELATIONSHIP', 'TRAVEL', 'UNDERSTANDING', 'FRIENDSHIP_WITH_BENEFITS', name='whatlookingforenum'), nullable=True),
    sa.Column('appearance', sa.String(), nullable=True),
    sa.Column('religion', sa.Enum('ATHEIST', 'ORTHODOX', 'CATHOLIC', 'MUSLIM', 'BUDDHIST', 'HINDU', 'SPIRITUAL', 'JUDAIST', 'OTHER', 'PREFERS_NOT_TO_SAY', name='religionenum'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_alcohol_attitude', 'user_attributes', ['alcohol_attitude'], unique=False)
    op.create_index('idx_children_preference', 'user_attributes', ['children_preference'], unique=False)
    op.create_index('idx_height', 'user_attributes', ['height'], unique=False)
    op.create_index('idx_religion', 'user_attributes', ['religion'], unique=False)
    op.create_index('idx_smoking_attitude', 'user_attributes', ['smoking_attitude'], unique=False)
    op.create_index('idx_what_looking_for', 'user_attributes', ['what_looking_for'], unique=False)
    op.create_index(op.f('ix_user_attributes_id'), 'user_attributes', ['id'], unique=False)
    op.alter_column('chats', 'user1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chats', 'user2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chats', 'deleted_for_user1',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chats', 'deleted_for_user2',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('date_invitations', 'status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'declined', name='invitation_status_enum'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('date_invitations', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dislikes', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('likes', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('likes', 'mutual',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('media', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('messages', 'deleted_for_user1',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('messages', 'deleted_for_user2',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('push_tokens', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscriptions', 'renewable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('temporary_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('transactions', 'transaction_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_transactions_payment_id', table_name='transactions')
    op.drop_index('ix_transactions_status', table_name='transactions')
    op.alter_column('user_geolocation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_geolocation', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_likes', 'total_likes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_likes', 'last_like_timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_photos', 'is_avatar',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_subscriptions', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_subscriptions', 'renewable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'verify',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('verification_queue', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('verification_queue', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_queue', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('verification_queue', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('users', 'verify',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'denied'::verificationstatus"),
               existing_nullable=True)
    op.alter_column('user_subscriptions', 'renewable',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user_subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user_subscriptions', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('user_photos', 'is_avatar',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('user_likes', 'last_like_timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('user_likes', 'total_likes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('user_geolocation', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('user_geolocation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.create_index('ix_transactions_status', 'transactions', ['status'], unique=False)
    op.create_index('ix_transactions_payment_id', 'transactions', ['payment_id'], unique=False)
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'INITIATED'::character varying"),
               existing_nullable=False)
    op.alter_column('transactions', 'transaction_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('temporary_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('subscriptions', 'renewable',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('push_tokens', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('messages', 'deleted_for_user2',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('messages', 'deleted_for_user1',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('media', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('likes', 'mutual',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('likes', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('dislikes', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('date_invitations', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('date_invitations', 'status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'declined', name='invitation_status_enum'),
               server_default=sa.text("'pending'::invitation_status_enum"),
               existing_nullable=True)
    op.alter_column('chats', 'deleted_for_user2',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('chats', 'deleted_for_user1',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('chats', 'user2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chats', 'user1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_user_attributes_id'), table_name='user_attributes')
    op.drop_index('idx_what_looking_for', table_name='user_attributes')
    op.drop_index('idx_smoking_attitude', table_name='user_attributes')
    op.drop_index('idx_religion', table_name='user_attributes')
    op.drop_index('idx_height', table_name='user_attributes')
    op.drop_index('idx_children_preference', table_name='user_attributes')
    op.drop_index('idx_alcohol_attitude', table_name='user_attributes')
    op.drop_table('user_attributes')
    # ### end Alembic commands ###
