"""Add appearence enums(prod)

Revision ID: d14a0f02ae61
Revises: 731ee7749873
Create Date: 2024-11-12 21:59:34.163837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd14a0f02ae61'
down_revision: Union[str, None] = '731ee7749873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chats', 'deleted_for_user1',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('chats', 'deleted_for_user2',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('date_invitations', 'status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'declined', name='invitation_status_enum'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('date_invitations', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dislikes', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('likes', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('likes', 'mutual',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)

    op.alter_column('media', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)

    op.alter_column('messages', 'deleted_for_user1',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('messages', 'deleted_for_user2',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('push_tokens', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscriptions', 'renewable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('temporary_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('transactions', 'transaction_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    # 1. Создание Enum типа 'appearanceenum'
    appearanceenum = postgresql.ENUM(
        'ACTIVE_LIFESTYLE',
        'FASHION_FORWARD',
        'NATURAL_SIMPLE',
        'REFINED_STYLE',
        'TATTOO_PIERCING',
        'TIMELY_CLASSIC',
        'EXPERIMENTAL_STYLE',
        'SOFT_KIND_APPEARANCE',
        name='appearanceenum'
    )
    appearanceenum.create(op.get_bind())

    # 2. Изменение типа столбца 'appearance' на 'appearanceenum' с явным преобразованием
    op.execute("""
        ALTER TABLE user_attributes
        ALTER COLUMN appearance TYPE appearanceenum
        USING (
            CASE
                WHEN appearance = 'Активный образ жизни и забота о теле.' THEN 'ACTIVE_LIFESTYLE'::appearanceenum
                WHEN appearance = 'Люблю моду и следую последним трендам.' THEN 'FASHION_FORWARD'::appearanceenum
                WHEN appearance = 'Предпочитаю натуральный и простой вид.' THEN 'NATURAL_SIMPLE'::appearanceenum
                WHEN appearance = 'Обожаю изысканный и утончённый стиль.' THEN 'REFINED_STYLE'::appearanceenum
                WHEN appearance = 'Носитель татуировок и пирсинга.' THEN 'TATTOO_PIERCING'::appearanceenum
                WHEN appearance = 'Предпочитаю вечную классику в одежде и внешности.' THEN 'TIMELY_CLASSIC'::appearanceenum
                WHEN appearance = 'Люблю выделяться и экспериментировать со стилем.' THEN 'EXPERIMENTAL_STYLE'::appearanceenum
                WHEN appearance = 'Внешность отражает мягкость и доброту.' THEN 'SOFT_KIND_APPEARANCE'::appearanceenum
                ELSE NULL
            END
        )
    """)
    op.alter_column('user_attributes', 'appearance',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ACTIVE_LIFESTYLE', 'FASHION_FORWARD', 'NATURAL_SIMPLE', 'REFINED_STYLE', 'TATTOO_PIERCING', 'TIMELY_CLASSIC', 'EXPERIMENTAL_STYLE', 'SOFT_KIND_APPEARANCE', name='appearanceenum'),
               existing_nullable=True)
    op.alter_column('user_geolocation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_geolocation', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_likes', 'total_likes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_likes', 'last_like_timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_photos', 'is_avatar',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_photos', 'scale',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_photos', 'position_x',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_photos', 'position_y',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_subscriptions', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'verify',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'is_subscription',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('verification_queue', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('verification_queue', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('verification_queue', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('verification_queue', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('users', 'is_subscription',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('users', 'verify',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'denied'::character varying"),
               existing_nullable=True)
    op.alter_column('user_subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user_subscriptions', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('user_photos', 'position_y',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=True)
    op.alter_column('user_photos', 'position_x',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=True)
    op.alter_column('user_photos', 'scale',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('1.0'),
               existing_nullable=True)
    op.alter_column('user_photos', 'is_avatar',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('user_likes', 'last_like_timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('user_likes', 'total_likes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('user_geolocation', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('user_geolocation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    # 1. Изменение типа столбца 'appearance' обратно на VARCHAR с явным преобразованием
    op.execute("""
        ALTER TABLE user_attributes
        ALTER COLUMN appearance TYPE VARCHAR
        USING (
            CASE
                WHEN appearance = 'ACTIVE_LIFESTYLE' THEN 'Активный образ жизни и забота о теле.'
                WHEN appearance = 'FASHION_FORWARD' THEN 'Люблю моду и следую последним трендам.'
                WHEN appearance = 'NATURAL_SIMPLE' THEN 'Предпочитаю натуральный и простой вид.'
                WHEN appearance = 'REFINED_STYLE' THEN 'Обожаю изысканный и утончённый стиль.'
                WHEN appearance = 'TATTOO_PIERCING' THEN 'Носитель татуировок и пирсинга.'
                WHEN appearance = 'TIMELY_CLASSIC' THEN 'Предпочитаю вечную классику в одежде и внешности.'
                WHEN appearance = 'EXPERIMENTAL_STYLE' THEN 'Люблю выделяться и экспериментировать со стилем.'
                WHEN appearance = 'SOFT_KIND_APPEARANCE' THEN 'Внешность отражает мягкость и доброту.'
                ELSE NULL
            END
        )
    """)

    # 2. Удаление Enum типа 'appearanceenum'
    appearanceenum = postgresql.ENUM(
        'ACTIVE_LIFESTYLE',
        'FASHION_FORWARD',
        'NATURAL_SIMPLE',
        'REFINED_STYLE',
        'TATTOO_PIERCING',
        'TIMELY_CLASSIC',
        'EXPERIMENTAL_STYLE',
        'SOFT_KIND_APPEARANCE',
        name='appearanceenum'
    )
    appearanceenum.drop(op.get_bind())
    op.alter_column('user_attributes', 'appearance',
               existing_type=sa.Enum('ACTIVE_LIFESTYLE', 'FASHION_FORWARD', 'NATURAL_SIMPLE', 'REFINED_STYLE', 'TATTOO_PIERCING', 'TIMELY_CLASSIC', 'EXPERIMENTAL_STYLE', 'SOFT_KIND_APPEARANCE', name='appearanceenum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('transactions', 'transaction_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('temporary_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('subscriptions', 'renewable',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('push_tokens', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('messages', 'deleted_for_user2',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('messages', 'deleted_for_user1',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)

    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('media', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    op.alter_column('likes', 'mutual',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('likes', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('dislikes', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('date_invitations', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('date_invitations', 'status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'declined', name='invitation_status_enum'),
               server_default=sa.text("'pending'::invitation_status_enum"),
               existing_nullable=True)
    op.alter_column('chats', 'deleted_for_user2',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('chats', 'deleted_for_user1',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    # ### end Alembic commands ###
