name: Docker CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Create .env file
      run: |
        echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
        echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
        echo ASYNC_DATABASE_URL=${{ secrets.ASYNC_DATABASE_URL }} >> .env
        echo MAIN_APP_HOST=${{ secrets.MAIN_APP_HOST }} >> .env
        echo MAIN_APP_PORT=${{ secrets.MAIN_APP_PORT }} >> .env
        echo MATCHES_APP_HOST=${{ secrets.MATCHES_APP_HOST }} >> .env
        echo MATCHES_APP_PORT=${{ secrets.MATCHES_APP_PORT }} >> .env
        echo ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }} >> .env
        echo REFRESH_TOKEN_EXPIRE_HOURS=${{ secrets.REFRESH_TOKEN_EXPIRE_HOURS }} >> .env
        echo YANDEX_KEY_ID=${{ secrets.YANDEX_KEY_ID }} >> .env
        echo YANDEX_KEY=${{ secrets.YANDEX_KEY }} >> .env
        echo BUCKET_MESSAGE_IMAGES=${{ secrets.BUCKET_MESSAGE_IMAGES }} >> .env
        echo BUCKET_MESSAGE_VOICES=${{ secrets.BUCKET_MESSAGE_VOICES }} >> .env
        echo BUCKET_PROFILE_IMAGES=${{ secrets.BUCKET_PROFILE_IMAGES }} >> .env
        echo BUCKET_VERIFY_IMAGES=${{ secrets.BUCKET_VERIFY_IMAGES }} >> .env
        echo SMS_API_KEY=${{ secrets.SMS_API_KEY }} >> .env
        echo FIREBASE_CREDENTIALS_PATH=${{ secrets.FIREBASE_CREDENTIALS_PATH }} >> .env
        echo VERIFY_CHAT_LINK=${{ secrets.VERIFY_CHAT_LINK }} >> .env
        echo VERIFY_SEND_TEXT=${{ secrets.VERIFY_SEND_TEXT }} >> .env
        echo VERIFY_CHAT_ID=${{ secrets.VERIFY_CHAT_ID }} >> .env

    - name: Build and push Docker image
      run: |
        docker-compose build -j 4
        docker-compose push

    - name: Add server to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to server using SSH action
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd swipe_api
          docker-compose pull
          docker-compose up -d

    - name: Send Telegram Notification
      if: always()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Build ${{ github.run_id }} of ${{ github.repository }} by ${{ github.actor }} completed.
          Status: ${{ job.status }}.