name: Docker CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    - name: Build Docker image
      run: |
        docker-compose build

    - name: Run tests (replace with your test command)
      run: |
        # If you have a specific command to run tests, replace the echo command with it.
        echo "Run your tests here. For example: docker-compose run --rm app your-test-command"
