name: Docker CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Push ${{ matrix.service }} image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [main_app, socket_app, push_app, admin_app]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get the version
      id: vars
      run: echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Login to Docker Hub using Token
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push ${{ matrix.service }} Docker image
      run: |
        docker build -t kirillka564/swipe_api:${{ matrix.service }}-${{ steps.vars.outputs.version }} ./${{ matrix.service }}
        docker push kirillka564/swipe_api:${{ matrix.service }}-${{ steps.vars.outputs.version }}

  deploy_to_server:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Add server to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to server using SSH action
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd swipe_api
          docker-compose pull
          docker-compose up -d
